offline_camera_calibration:
  ros__parameters:

    minimum_valid_images: 21

    chessboard_size: [7, 9]
    square_size: 30.0 # mm

    image_size: [512, 512] # (width, height)
    
    images_path: /home/marco/xarm_devel/src/AA_Resources_Calibration/tasi_left_cam_calibration/512x512/
    calibration_path: /home/marco/xarm_devel/src/AA_Resources_Calibration/tasi_left_cam_calibration/512x512/calibration/

    calibration_file: calib_cam.xml