calibration_node:
  ros__parameters:
    board_dim: [8, 6]

    subscribers:
      camera: /camera/raw_frame

    auto_capture:
      mode: True            # Capture an image every
      time_for_frame: 1.0   # sec
    
    calibration_path: auto  # Specify absolute path instead
