av_node:
  ros__parameters:
    publishers:
      raw_frame: /parking_camera/raw_frame

    services:
      stop_camera: /parking_camera/get_cam_state

    frames: 
      camera_link: parking_camera_link
      
    flip_vertically: False
    flip_horizontally: False